# Generated by Django 6.0.2 on 2026-06-07 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatare/', verbose_name='Avatar')),
                ('sprache', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano')], default='de', max_length=5, verbose_name='Sprache')),
                ('telefon', models.CharField(blank=True, max_length=60, verbose_name='Telefon')),
                ('strasse', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('plz', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('stadt', models.CharField(blank=True, max_length=120, verbose_name='Stadt')),
                ('land', models.CharField(blank=True, max_length=120, verbose_name='Land')),
                ('eingeloggt', models.BooleanField(default=False, verbose_name='Eingeloggt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Teilnehmer',
                'verbose_name_plural': 'Teilnehmer',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('teilnehmer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangobase.teilnehmer')),
                ('anbietername', models.CharField(blank=True, max_length=200, verbose_name='Anbieter-Name')),
                ('logo', models.ImageField(blank=True, upload_to='anbieter/', verbose_name='Logo')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('verifiziert', models.BooleanField(default=False, verbose_name='Verifiziert')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Provider',
            },
            bases=('djangobase.teilnehmer',),
        ),
    ]
