# Generated by Django 6.0.2 on 2026-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='anwesend',
            field=models.BooleanField(default=False, verbose_name='Anwesend'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='ui',
            field=models.PositiveIntegerField(default=1, verbose_name='UI'),
        ),
    ]
