# Generated by Django 6.0.2 on 2026-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0002_teilnehmer_anwesend_teilnehmer_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='avatar_emoji',
            field=models.CharField(blank=True, max_length=8, verbose_name='Avatar (Emoji)'),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatare/', verbose_name='Avatar-Bild'),
        ),
    ]
