# Generated by Django 6.0.6 on 2026-06-11 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0003_teilnehmer_avatar_emoji_alter_teilnehmer_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seitenaufruf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zeit')),
                ('pfad', models.CharField(db_index=True, max_length=300, verbose_name='Pfad')),
                ('typ', models.CharField(choices=[('html', 'Seite'), ('json', 'JSON/API'), ('andere', 'Andere')], default='html', max_length=8, verbose_name='Typ')),
                ('land', models.CharField(blank=True, max_length=2, verbose_name='Land (ISO)')),
                ('besucher', models.CharField(db_index=True, max_length=16, verbose_name='Besucher-Hash')),
                ('geraet', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobil'), ('tablet', 'Tablet')], default='desktop', max_length=8, verbose_name='Gerät')),
                ('referrer', models.CharField(blank=True, max_length=120, verbose_name='Referrer-Domain')),
                ('bot', models.BooleanField(default=False, verbose_name='Bot')),
                ('groesse', models.PositiveBigIntegerField(default=0, verbose_name='Antwortgröße (Bytes)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Seitenaufruf',
                'verbose_name_plural': 'Seitenaufrufe',
            },
        ),
    ]
