# Generated by Django 6.0.6 on 2026-06-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0004_seitenaufruf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextQuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schluessel', models.CharField(max_length=64, unique=True, verbose_name='Schlüssel')),
                ('quelle', models.TextField(verbose_name='Deutscher Text')),
                ('zuletzt_gesehen', models.DateTimeField(auto_now=True, verbose_name='Zuletzt gesehen')),
            ],
            options={
                'verbose_name': 'Textquelle',
                'verbose_name_plural': 'Textquellen',
            },
        ),
        migrations.CreateModel(
            name='Uebersetzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprache', models.CharField(max_length=8, verbose_name='Sprache')),
                ('text', models.TextField(verbose_name='Übersetzung')),
                ('quelle_hash', models.CharField(max_length=32, verbose_name='Quell-Hash')),
                ('uebersetzt_am', models.DateTimeField(auto_now=True, verbose_name='Übersetzt am')),
                ('quelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebersetzungen', to='djangobase.textquelle', verbose_name='Quelle')),
            ],
            options={
                'verbose_name': 'Übersetzung',
                'verbose_name_plural': 'Übersetzungen',
                'constraints': [models.UniqueConstraint(fields=('quelle', 'sprache'), name='uebersetzung_quelle_sprache')],
            },
        ),
    ]
