# Generated by Django 6.0.6 on 2026-06-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0005_textquelle_uebersetzung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verbrauch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zeit')),
                ('typ', models.CharField(choices=[('tile', 'Kartenkacheln'), ('route', 'Navigation/Routing')], db_index=True, max_length=8, verbose_name='Typ')),
                ('anzahl', models.PositiveIntegerField(default=1, verbose_name='Anzahl')),
                ('bytes', models.PositiveBigIntegerField(default=0, verbose_name='Bytes')),
                ('detail', models.CharField(blank=True, max_length=40, verbose_name='Detail')),
            ],
            options={
                'verbose_name': 'Verbrauch',
                'verbose_name_plural': 'Verbrauch',
            },
        ),
    ]
