# Generated by Django 6.0.6 on 2026-06-11 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0006_verbrauch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='email_bestaetigt_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-Mail bestätigt am'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='freigegeben_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben am'),
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='registriert_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registriert am'),
        ),
        migrations.CreateModel(
            name='LoginSitzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benutzer', models.CharField(max_length=200, verbose_name='Benutzer (Snapshot)')),
                ('beginn', models.DateTimeField(db_index=True, verbose_name='Login')),
                ('ende', models.DateTimeField(blank=True, null=True, verbose_name='Logout')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_sitzungen', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Login-Sitzung',
                'verbose_name_plural': 'Login-Sitzungen',
                'ordering': ['-beginn'],
            },
        ),
    ]
