# Generated by Django 6.0.6 on 2026-06-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0007_teilnehmer_email_bestaetigt_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='zuletzt_aktiv',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt aktiv'),
        ),
    ]
